GUACAMOLE-1064: add Norwegian keyboard
apache/guacamole-server pull request #342
Opened 2021-05-28 11:46 UTC by oharboe

@jmoehlma Best guess... How do I test this?

2021-05-28 12:06 UTC, necouchman commented
@oharboe: Looks fine without having an actual keyboard to test it with. Unfortunately I don't have a way to test, either :smile:

2021-05-28 13:04 UTC, oharboe commented
@necouchman Is there a way to test this beyond manual integration testing, i.e. set up a couple of machines w/Guacamole?

2021-05-28 22:59 UTC, mike-jumper commented
@oharboe, no, there is no automated test mechanism for keyboard layout behavior. The only way to test that a new keyboard layout behaves correctly is to deploy and directly test against an RDP connection using that layout.

2021-06-01 13:16 UTC, oharboe commented
@mike-jumper Tested. Seems to work :-)

`sudo showkey` was useful to find scancodes.

2021-06-03 01:31 UTC, mike-jumper requested changes
Except for the ordering of the keymaps (see comment), this LGTM.

2021-06-03 01:31 UTC, mike-jumper commented on src/protocols/rdp/Makefile.am
> +    $(srcdir)/keymaps/no_no_qwerty.keymap
With the exception of "base" and "failsafe" (which are special cases) and "da_dk_qwerty" (which somehow slipped in here unsorted), the files listed here are being maintained in sorted order. Please move your new keymap up in the list such that sorted order is maintained.

2021-06-03 05:34 UTC, mike-jumper approved these changes

2021-06-03 05:34 UTC, merged