GUACAMOLE-1997: Fix issue on screen resize with freerdp >= 3.8.0.
apache/guacamole-server pull request #563
Opened 2024-11-04 20:36 UTC by corentin-soriano

With freerdp >= 3.8.0, we can't resize with "display-update":

 ```
guacd[609180]: DEBUG:   Display update channel will be used for display size changes.
guacd[609180]: DEBUG:   {Microsoft::Windows::RDS::DisplayControl:16} OnOpen=(nil), OnClose=0x7f40b610b150
guacd[609180]: DEBUG:   Server resized display to 768x583
GUAC_ASSERT in guac_rdp_gdi_end_paint() failed at gdi.c:102.
guacd[609080]: INFO:    Connection "$3ec11dae-60d9-4820-9028-01a10f4e95f4" removed.
guacd[609080]: DEBUG:   Unable to request termination of client process: No such process 
guacd[609080]: DEBUG:   All child processes for connection "$3ec11dae-60d9-4820-9028-01a10f4e95f4" have been terminated. 
```

Caused by this bugfix in freerdp: https://github.com/FreeRDP/FreeRDP/pull/10488
Freerdp triggers EndPaint first when resizing to ensure there are no unfinished BeginPaints.

2024-11-04 22:23 UTC, mike-jumper commented
> Freerdp triggers EndPaint first when resizing to ensure there are no unfinished BeginPaints.

I'm a little concerned about that fix in FreeRDP/FreeRDP#10488. Triggering an `EndPaint` without a corresponding `BeginPaint` sounds like broken behavior. I see a check in the FreeRDP PR that verifies whether `BeginPaint` was called, but that check doesn't happen until _after_ `EndPaint` has been called.

I'll read through the surrounding code on our end a bit deeper, but my main concern is that this change in behavior could cause a race condition in the handling of "Display Update" vs. GDI updates.

2024-11-04 22:23 UTC, mike-jumper requested changes

2024-11-05 07:26 UTC, corentin-soriano commented on src/protocols/rdp/gdi.c
> +    /* Handle the case where EndPaint was called without BeginPaint */
Documentation added!
Is this clear enough?

2024-11-09 08:42 UTC, mike-jumper commented on src/protocols/rdp/gdi.c
> +    /* Handle the case where EndPaint was called without BeginPaint */
Yep - much better. Many thanks.

2024-11-09 08:42 UTC, mike-jumper approved these changes

2024-11-09 08:59 UTC, merged